<?php

/** @var Magenest\DeliveryTime\Block\Order\View\DeliveryInformation $block */
$data              = $block->getDeliveryInformation();
$houseSecurityCode = $data->getData('houseSecurityCode');
$deliveryComment   = $data->getData('deliveryComment');
$deliveryDate      = $data->getData('deliveryDate');
$deliveryTime      = $data->getData('deliveryTime');
?>

<div class="box-content delivery-information">
    <?php if ($deliveryDate || $deliveryTime) : ?>
        <br><strong><?= $block->escapeHtml(__('Delivery On:')) ?></strong>
        <br><span><?= $block->escapeHtml($deliveryTime) ?></span>
        <br><span><?= $block->escapeHtml($deliveryDate) ?></span>
    <?php endif; ?>

    <?php if ($houseSecurityCode) : ?>
        <br><strong><?= $block->escapeHtml(__('House Security Code:')) ?></strong>
        <br><span><?= $block->escapeHtml($houseSecurityCode) ?></span>
    <?php endif; ?>

    <?php if ($deliveryComment) : ?>
        <br><strong><?= $block->escapeHtml(__('Delivery Comment:')) ?></strong>
        <br><span><?= $block->escapeHtml($deliveryComment) ?></span>
    <?php endif; ?>
</div>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('.box-order-shipping-method').append($('.delivery-information'));
    });
</script>
